Fix for missing exports from sfc
sfc-model adds ietf-acl.yang and packet-fields.yang but does not export them so other bundles fail to resolve when loading since they can't find them.

org.osgi.framework.BundleException: The bundle "org.opendaylight.ovsdb.ovssfc_0.0.1.SNAPSHOT [137]" could not be resolved. Reason: Missing Constraint: Import-Package: org.opendaylight.yang.gen.v1.urn.ietf.params.xml.ns.yang.ietf.acl.rev140520; version="[0.0.0,1.0.0)"

Change-Id: Id1db0f3c6cd666c6e5f463e94f81a99304a4532c
Signed-off-by: Sam Hague <shague@redhat.com>