Update patch set 7
Patch Set 7: Code-Review-1

Using VXLAN-GPE + ETH + NSH, when doing ssh traffic the packet size gets very big and then vxlan_tool.py fails with this:

Traceback (most recent call last):
  File "vxlan_tool.py", line 798, in <module>
    main()
  File "vxlan_tool.py", line 794, in main
    sent = send_s.send(pkt)
socket.error: [Errno 90] Message too long

For HTTP traffic it works correctly. In the old vxlan_tool.py, when vxlan-gpe + NSH and SSH it used to work so maybe there is something missing in the new implementation?

Patch-set: 7
Reviewer: Gerrit User 6016 <6016@7fc14799-209e-464c-9743-7a06c2c21a81>
Label: Code-Review=-1