Update patch set 1
Patch Set 1:

Netconf -all- test job [0] is failing and this is visible in karaf.log [1]:

2016-12-12 13:08:45,193 | ERROR | config-pusher    | ConfigPusherImpl                 | 135 - org.opendaylight.controller.config-persister-impl - 0.6.0.SNAPSHOT | Unable to push configuration due to missing yang models. Yang models that are missing, but required by the configuration: [urn:opendaylight:params:xml:ns:yang:controller:config:sfc-provider:impl?module=sfc-provider-impl&revision=2014-06-30]. For each mentioned model check:  1. that the mentioned yang model namespace/name/revision is identical to those in the yang model itself 2. the yang file is present in the system 3. the bundle with that yang file is present in the system and active 4. the yang parser did not fail while attempting to parse that model
2016-12-12 13:08:45,193 | ERROR | config-pusher    | ConfigPusherImpl                 | 135 - org.opendaylight.controller.config-persister-impl - 0.6.0.SNAPSHOT | Failed to apply configuration snapshot: sfc-test-consumer-initial.xml(odl-integration-compatible-with-all,odl-integration-compatible-with-all)
java.lang.IllegalStateException: Unable to push configuration due to missing yang models. Required yang models that are missing: [urn:opendaylight:params:xml:ns:yang:controller:config:sfc-provider:impl?module=sfc-provider-impl&revision=2014-06-30]
	at org.opendaylight.controller.config.persist.impl.ConfigPusherImpl.waitForCapabilities(ConfigPusherImpl.java:204)[135:org.opendaylight.controller.config-persister-impl:0.6.0.SNAPSHOT]
	at org.opendaylight.controller.config.persist.impl.ConfigPusherImpl.pushConfigWithConflictingVersionRetries(ConfigPusherImpl.java:154)[135:org.opendaylight.controller.config-persister-impl:0.6.0.SNAPSHOT]
	at org.opendaylight.controller.config.persist.impl.ConfigPusherImpl.internalPushConfigs(ConfigPusherImpl.java:124)[135:org.opendaylight.controller.config-persister-impl:0.6.0.SNAPSHOT]
	at org.opendaylight.controller.config.persist.impl.ConfigPusherImpl.processSingle(ConfigPusherImpl.java:78)[135:org.opendaylight.controller.config-persister-impl:0.6.0.SNAPSHOT]
	at org.opendaylight.controller.config.persist.impl.ConfigPusherImpl.process(ConfigPusherImpl.java:70)[135:org.opendaylight.controller.config-persister-impl:0.6.0.SNAPSHOT]
	at org.opendaylight.controller.config.persist.impl.osgi.ConfigPersisterActivator$2.run(ConfigPersisterActivator.java:131)[135:org.opendaylight.controller.config-persister-impl:0.6.0.SNAPSHOT]
	at java.lang.Thread.run(Thread.java:745)[:1.8.0_111]
Caused by: org.opendaylight.controller.config.persist.impl.ConfigPusherImpl$NotEnoughCapabilitiesException: Not enough capabilities for sfc-test-consumer-initial.xml(odl-integration-compatible-with-all,odl-integration-compatible-with-all). Expected but not found: [urn:opendaylight:params:xml:ns:yang:controller:config:sfc-provider:impl?module=sfc-provider-impl&revision=2014-06-30]
	at org.opendaylight.controller.config.persist.impl.ConfigPusherImpl.waitForCapabilities(ConfigPusherImpl.java:184)[135:org.opendaylight.controller.config-persister-impl:0.6.0.SNAPSHOT]
	... 6 more


Not sure whether it is SFC who causes the delayed start of netconf, but I think this Change improves SFC regardless.

Sandbox test under way.

[0] https://jenkins.opendaylight.org/releng/view/netconf/job/netconf-csit-1node-userfeatures-all-carbon/117/
[1] https://logs.opendaylight.org/releng/jenkins092/netconf-csit-1node-userfeatures-all-carbon/117/archives/karaf.log.gz

Patch-set: 1