Update patch set 8
Patch Set 8:

The Yang models in this patch do not pass IETF muster. Since this is all new please fix all pyang compilation errors before committing. It should be fairly quickly since you only have 2 models. 

Example of pyang --ietf ioam-scv.yang output below. The first warning you can ignore of course.

REPENNO-M-L9FE:Desktop repenno$ pyang --ietf ioam-scv.yang
ioam-scv.yang:5: warning: IETF rule (RFC 6087: 4.8): namespace value should be "urn:ietf:params:xml:ns:yang:ioam-scv"
ioam-scv.yang:9: error: module "sfc-common" not found in search path
ioam-scv.yang:24: error: IETF rule (RFC 6087: 4.7): statement "revision" must have a "reference" substatement
ioam-scv.yang:93: warning: IETF rule (RFC formatting): line length 71 exceeds 70 characters
ioam-scv.yang:102: warning: IETF rule (RFC formatting): line length 72 exceeds 70 characters
ioam-scv.yang:111: warning: IETF rule (RFC formatting): line length 72 exceeds 70 characters
ioam-scv.yang:121: warning: IETF rule (RFC formatting): line length 73 exceeds 70 characters
ioam-scv.yang:127: warning: IETF rule (RFC formatting): line length 72 exceeds 70 characters
ioam-scv.yang:148: warning: IETF rule (RFC formatting): line length 73 exceeds 70 characters
ioam-scv.yang:157: error: IETF rule (RFC 6087: 4.12): statement "leaf" must have a "description" substatement
ioam-scv.yang:168: error: IETF rule (RFC 6087: 4.12): statement "leaf" must have a "description" substatement
ioam-scv.yang:190: warning: IETF rule (RFC 6087: 4.3): statement "mandatory" is given with its default value "false"

Patch-set: 8
Reviewer: Gerrit User 248 <248@7fc14799-209e-464c-9743-7a06c2c21a81>
Label: Verified=0